create database mydatabase;
use mydatabase;
select * from mytable;

-- 1> what is the total revenue generated by male vs female customer
select gender,sum(purchase_amount)as revenue
from mytable group by gender;

-- 2> which customer used a discount but still spent more than the average purchase_amout
select customer_id,purchase_amount from mytable 
where discount_applied = 'Yes' and 
purchase_amount >=(select avg(purchase_amount) from mytable);

-- 3> what are the top 5 products with highest average review rating
select item_purchased, Round(avg(review_rating),2) as "Average_Product_Rating"
from mytable group by item_purchased order by 
avg(review_rating) desc limit 5;

-- 4>compare the average purchase amount between standard and express shipping
select shipping_type, Round(avg(purchase_amount),2) from mytable
where shipping_type in('Standard','Express') group by shipping_type;

-- 5> do Subscribe customers spend more? compare average spend and total revenue between subsrcibes and non-subsrcibers
select subscription_status, Count(customer_id)as total_customers,
Round(avg(purchase_amount),2) as avg_spend,
Round(sum(purchase_amount),2) as total_revenue from mytable group by 
subscription_status order by total_revenue,avg_spend desc;

-- 6> which product have heighest percentage of purchase with dicounts applied
select item_purchased, Round(sum(case when discount_applied = 'Yes' 
then 1 else 0 end)/count(*)*100,2)as discount_rate from mytable
group by item_purchased order by discount_rate desc limit 5;

-- 7> Segment customers into new,returning and loyal based on their total number of
-- previous purchase and show the count of each segment  
with customer_type as ( select customer_id,previous_purchases,
Case 
   when previous_purchases = 1 then 'New'
   when previous_purchases between 2 and 10 then 'Returning'
   else 'Loyal'
   end as customer_segment
from mytable 
) 
select customer_segment,count(*) as 'Number of Customers' from customer_type
group by customer_segment;

-- 8> what are the top 3 most purchased products within each category ?
with item_counts as (select category,item_purchased,count(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id) desc) as item_rank
from mytable group by category,item_purchased
)
select item_rank,category,item_purchased,total_orders 
from item_counts where item_rank <= 3;

-- 9> are customer who are repeat buyers (more than 5 previous purchases) also likely to subscribe
select subscription_status, count(customer_id) as repeat_buyers from mytable
where previous_purchases > 5 group by subscription_status;

-- 10> what is the revenue contribution of each age group
select age_group, sum(purchase_amount) as total_revenue from mytable
group by age_group order by total_revenue desc;




